baseurl = "https://www.computersaysyes.nl"
DefaultContentLanguage = "en"
title = ""
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Welcome to Computer Says Yes!"
  mainSections = ["post","posts"]
  logo = "img/logo_small.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Params.Author]
  name = "Tim Bosua"
  website = "computersaysyes.nl"
  email = "tim@computersaysyes.nl"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    parent = "over"
    name = "Over"
    url = "post/2023-10-17-over"
    weight = 1

[[menu.main]]
    identifier = "welkom"
    name = "Welkom"
    weight = 2

[[menu.main]]
    parent = "welkom"
    name = "Welkom"
    url = "post/2023-10-05-welkom"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
