baseurl = "https://www.computersaysyes.nl"
DefaultContentLanguage = "en"
title = ""
theme = "beautifulhugo"
enableEmoji = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pagination.pagerSize = 3
enableInlineShortcodes = true
enableGitInfo = true
enableRobotsTXT = true
selfHosted = true

[params]
  subtitle = "Welcome to Computer Says Yes!"
  mainSections = ["post","posts"]
  logo = "img/logo_small.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  since = "2017"
    [params.author]
        name = "Tim Bosua"
    [params.contact]
        name = "Tim Bosua"
        website = "computersaysyes.nl"
        email = "tim@computersaysyes.nl"
        phone = '+31 6 27 01 67 98'
    [params.copyright]
        prefix = ""
        holder = "Tim Bosua"
        startYear = "2017"
        suffix = ""
    [params.info]
        title404 = "Deze pagina bestaat niet!"

[[menu.main]]
    parent = "over"
    name = "Over mij"
    url = "page/about"
    weight = 1

[[menu.main]]
    parent = "over"
    name = "Contact"
    url = "post/2024-04-09-contact"
    weight = 1

[[menu.main]]
    parent = "over"
    name = "Over CSY"
    url = "post/2023-10-17-over"
    weight = 1

[[menu.main]]
    identifier = "welkom"
    name = "Welkom"
    url = "post/2024-04-03-welkom"
    weight = 2
