baseURL = "https://www.computersaysyes.nl"
title = ""
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true

[params]
author = "Computer Says Yes"
info = ["Welkom bij Computer Says Yes!"]
subtitle = "Welcome to Computer Says Yes!"
colorScheme = "auto"
avatarURL = "img/logo_small.png"
favicon = "img/favicon.ico"
dateFormat = "October 6, 2026"
since = "2017"

[params.contact]
name = "Tim Bosua"
website = "computersaysyes.nl"
email = "tim@computersaysyes.nl"
phone = '+31 6 27 01 67 98'

[params.copyright]
prefix = ""
holder = "Tim Bosua"
startYear = "2017"
suffix = ""

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/timbosua"

[[languages.en.menu.main]]
name = "Over"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projecten"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 3
url = "contact/"
